## Fazer previsao de classe.


# Import Libraries

In [31]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn import metrics as mt


#  Looad Dataset

In [32]:
data = pd.read_csv('train.csv')
df = data.copy()

# Data Preparation

In [33]:
feactures = ['idade', 'divida_atual', 'renda_anual',
       'valor_em_investimentos', 'taxa_utilizacao_credito', 'num_emprestimos',
       'num_contas_bancarias', 'num_cartoes_credito', 'dias_atraso_dt_venc',
       'num_pgtos_atrasados', 'num_consultas_credito', 'taxa_juros']
label = ['saldo_atual']       

In [34]:
X_tarin = df.loc[:, feactures]
y_train = df.loc[:, label]

In [35]:
dfc = pd.concat([X_tarin,y_train], axis=1)
dfc.head()

idade  divida_atual  renda_anual  valor_em_investimentos  \
0     21       2577.05  24196.89636              104.306544   
1     40       2465.39  19227.37796               69.858778   
2     36       1055.29  42822.28223              134.201478   
3     58        703.05  51786.82600              297.350067   
4     35        891.29  44626.85346              134.201478   

   taxa_utilizacao_credito  num_emprestimos  num_contas_bancarias  \
0                31.038763                6                     5   
1                36.917093                5                     8   
2                34.561714                0                     3   
3                31.493561                0                     3   
4                28.028887                2                     8   

   num_cartoes_credito  dias_atraso_dt_venc  num_pgtos_atrasados  \
0                    7                   21                   14   
1                    5                   40                   23   
2                    6                   26                   13   
3                    7                   12                    7   
4                    7                   24                   10   

   num_consultas_credito  taxa_juros  saldo_atual  
0                      9          15   278.172008  
1                     10          18   268.874152  
2                      3          15   446.643127  
3                      2           1   321.141267  
4                      8          20   428.716114

# Model Training

In [36]:
# Model definition
lr_model = LinearRegression() # exemplo de modeledo da linear refgression

#  model fit ( ajuste de treinamento)
lr_model.fit(X_tarin, y_train)

#  previsao
y_pred = lr_model.predict(X_tarin)

In [37]:
# fazer algumas previsoes
df1 = df.loc[:, ['id_cliente','saldo_atual']]
# criar uma coluna predict
df1['predict'] = y_pred
df1.head()

id_cliente  saldo_atual     predict
0        1767   278.172008  346.669549
1       11920   268.874152  367.840277
2        8910   446.643127  431.468979
3        4964   321.141267  445.506463
4       10100   428.716114  378.271169

In [38]:
y_pred # Os valores

array([[346.66954862],
       [367.84027655],
       [431.46897895],
       ...,
       [412.25174802],
       [400.68529863],
       [455.26482252]])

In [39]:
np.sum( (X_tarin.loc[0,].values * lr_model.coef_) ) + lr_model.intercept_

array([346.66954862])

In [40]:
# fazendo o msm processo com o laco for
for i in range( len(X_tarin) ):
    print( np.sum( ( X_tarin.loc[i,].values * lr_model.coef_ ) ) + lr_model.intercept_)
    if i == 10:
        break 

[346.66954862]
[367.84027655]
[431.46897895]
[445.50646329]
[378.27116865]
[352.4833463]
[410.60408532]
[210.68563909]
[388.61996465]
[301.1477063]
[158.0964866]


In [41]:
lr_model.coef_ # coeficientes d reta

array([[ 3.96706202e-04, -4.00595601e-02,  2.77622532e-06,
        -1.04318668e-03,  9.80890872e+00, -1.22353405e-02,
        -6.33015538e-03, -3.57808095e-03, -2.15858165e+00,
         3.77570060e-04,  6.79176336e-03,  3.48471845e-03]])

In [42]:
lr_model.intercept_ # eu pegando esse comando ele e meu paramentro a0 esse valo er e construido usando os minimos quadrado

array([190.82359144])

In [43]:
# msm que pegar a formula la em baixo
y = lr_model.intercept_ + lr_model.coef_[0][0] * X_tarin.iloc[0,0] # e assim vai ex: a2x...

In [44]:


# # estamos fazendo isso --> y = a + bx

# # com essa formula temos isso aqui -->
# y = a0 +  a1x1 +  a2x2 + a1x1 + a3x3 + a4x4 +... a12x12

# a0 = # parametros das retas que desenhamos . Sao meus parametros 
# a1 =
# a2 =
# a3 =
# a4 =
# ...
# a12 =

# x1 = # Sao minhas variaveis da feactures ou seja minhas colunas 
# x2 = 
# x3 = 
# x4 = 
# ... 
# x12 = 

# R2 Na Pratica

In [45]:
# 2.0 Seleção de Features
features = ['idade', 'divida_atual', 'renda_anual', 'valor_em_investimentos',
            'taxa_utilizacao_credito', 'num_emprestimos', 'num_contas_bancarias', 
            'num_cartoes_credito', 'dias_atraso_dt_venc', 'num_pgtos_atrasados', 'num_consultas_credito',
            'taxa_juros']
label = ['saldo_atual']

x_train = df.loc[:, features] 
y_train = df.loc[:, label]

# 3.0 Model Training
lr_model = LinearRegression() 
lr_model.fit( x_train, y_train )

#Predition
y_pred = lr_model.predict( x_train )

df1 = df.loc[:, ['id_cliente', 'saldo_atual']] 
df1['predicted'] = y_pred

df1.head()


id_cliente  saldo_atual   predicted
0        1767   278.172008  346.669549
1       11920   268.874152  367.840277
2        8910   446.643127  431.468979
3        4964   321.141267  445.506463
4       10100   428.716114  378.271169

# Performace

In [46]:
mt.r2_score(y_train, y_pred)

0.16917364489050024

In [47]:
# 4.0 Model Performance
r2_squared = np.round( 100*mt.r2_score( y_train, y_pred ), 2 ) 
print( 'R2 square: {}%'.format( r2_squared ) )


R2 square: 16.92%


## Model Training - Statsmodels

In [48]:
import statsmodels.formula.api as smf
import statsmodels.api as sm

# Definição do modelo
lr_model = smf.ols(formula='saldo_atual ~ idade + divida_atual + num_emprestimos', data=df)

# Treinamento do modelo
lr_model = lr_model.fit()

# Teste de ANOVA
anova_result = sm.stats.anova_lm(lr_model, typ=1)
anova_result

df        sum_sq       mean_sq            F  \
idade               1.0  4.085925e+02  4.085925e+02     0.009575   
divida_atual        1.0  4.494005e+07  4.494005e+07  1053.104993   
num_emprestimos     1.0  3.976109e+03  3.976109e+03     0.093174   
Residual         9496.0  4.052309e+08  4.267385e+04          NaN   

                        PR(>F)  
idade             9.220529e-01  
divida_atual     3.537135e-219  
num_emprestimos   7.601864e-01  
Residual                   NaN

# Model Training

In [49]:
# Model definition
lr_model = LinearRegression() # exemplo de modeledo da linear refgression

#  model fit ( ajuste de treinamento)
lr_model.fit(X_tarin, y_train)

#  previsao
y_pred = lr_model.predict(X_tarin)

In [50]:
df3 = pd.concat( [ X_tarin, y_train ], axis=1 )
df3.head()

idade  divida_atual  renda_anual  valor_em_investimentos  \
0     21       2577.05  24196.89636              104.306544   
1     40       2465.39  19227.37796               69.858778   
2     36       1055.29  42822.28223              134.201478   
3     58        703.05  51786.82600              297.350067   
4     35        891.29  44626.85346              134.201478   

   taxa_utilizacao_credito  num_emprestimos  num_contas_bancarias  \
0                31.038763                6                     5   
1                36.917093                5                     8   
2                34.561714                0                     3   
3                31.493561                0                     3   
4                28.028887                2                     8   

   num_cartoes_credito  dias_atraso_dt_venc  num_pgtos_atrasados  \
0                    7                   21                   14   
1                    5                   40                   23   
2                    6                   26                   13   
3                    7                   12                    7   
4                    7                   24                   10   

   num_consultas_credito  taxa_juros  saldo_atual  
0                      9          15   278.172008  
1                     10          18   268.874152  
2                      3          15   446.643127  
3                      2           1   321.141267  
4                      8          20   428.716114

In [51]:
# fazer algumas previsoes
df1 = df.loc[:, ['id_cliente','saldo_atual']]
# criar uma coluna predict
df1['predict'] = y_pred
df1.head()

id_cliente  saldo_atual     predict
0        1767   278.172008  346.669549
1       11920   268.874152  367.840277
2        8910   446.643127  431.468979
3        4964   321.141267  445.506463
4       10100   428.716114  378.271169

# Calculo manual das metricas SSE, SSR, SST

In [52]:
import statsmodels.api as sm
# Define a variavel
x = df.loc[:, ['idade', 'divida_atual', 'renda_anual','num_emprestimos']]

# Define Predictor
y = df.loc[:, label]

# Add constant to predctor variables
y = sm.add_constant(y)

#  fit lenear regresion model
model = sm.OLS(x, y).fit()

import numpy as np

#  Calcular o SSE
sse = np.sum((model.fittedvalues - df.loc[:,['idade', 'divida_atual', 'renda_anual','num_emprestimos']]) ** 2)

# Calcular o ssr
ssr = np.sum((model.fittedvalues - df.loc[:, ['idade', 'divida_atual', 'renda_anual','num_emprestimos']].mean() ) ** 2)

# Calcular o ssto
ssto = ssr + sse

print(sse)
print(ssr)
print(ssto)

idade              4.457633e+09
divida_atual       1.143185e+10
renda_anual        2.007940e+16
num_emprestimos    3.716838e+07
dtype: float64
idade              4.045884e+03
divida_atual       1.267789e+09
renda_anual        1.014813e+13
num_emprestimos    2.920434e+03
dtype: float64
idade              4.457637e+09
divida_atual       1.269964e+10
renda_anual        2.008955e+16
num_emprestimos    3.717130e+07
dtype: float64


In [53]:
# print(lr_model.summary())

In [54]:
# print(model.summary())

# Performace

In [55]:
# all
mt.r2_score(y_train, y_pred)

0.16917364489050024

In [56]:
# Idade mais divida atual
mt.r2_score(y_train, y_pred)

0.16917364489050024

In [57]:
# Idade 
mt.r2_score(y_train, y_pred)

0.16917364489050024

In [58]:
# Idade Divida atual e renda anual
mt.r2_score(y_train, y_pred)

0.16917364489050024

# RMSE na prática

In [59]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression 
from sklearn import metrics as mt

# 1.0 Load dataset
df = pd.read_csv( 'train.csv' )

# 2.0 Seleção de Features
features = ['idade', 'divida_atual', 'renda_anual', 'valor_em_investimentos',
            'taxa_utilizacao_credito', 'num_emprestimos', 'num_contas_bancarias', 
            'num_cartoes_credito', 'dias_atraso_dt_venc', 'num_pgtos_atrasados', 
            'num_consultas_credito', 'taxa_juros']
label = ['saldo_atual']

x_train = df.loc[:, features] 
y_train = df.loc[:, label]

# 3.0 Model Training
lr_model = LinearRegression() 
lr_model.fit( x_train, y_train )

y_pred = lr_model.predict( x_train )

df1 = df.loc[:, ['id_cliente', 'saldo_atual']] 
df1['predicted'] = y_pred

# 4.0 Model Performance
## 4.1 R squared
r2_squared = np.round( 100*mt.r2_score( y_train, y_pred ), 2 ) 
print( 'R2 square: {}%'.format( r2_squared ) )

## 4.2 MSE
mse = np.round( mt.mean_squared_error( y_train, y_pred ) , 2 ) 
print( 'A cada previsão, o erro médio é de: U${}'.format( mse ) )

## 4.3 RMSE
rmse = np.sqrt( mse )
print( 'A cada previsão, o erro médio é de: U${}'.format( rmse ) )

# 5.0 Conclusão
print( '{}% da variação da variável alvo y é reduzida, levando em consideração o preditor'.format( r2_squared ) ) 
print( '{}% da variação da variável alvo y é “explicada pela variação do preditor x'.format( r2_squared ) )

R2 square: 16.92%
A cada previsão, o erro médio é de: U$39370.27
A cada previsão, o erro médio é de: U$198.41942949217446
16.92% da variação da variável alvo y é reduzida, levando em consideração o preditor
16.92% da variação da variável alvo y é “explicada pela variação do preditor x


# Metricas de avaliacao MSE  

- MSE ( Mean Square Error ) calcula a média do quadrado das diferenças entre os valores reais e preditos.
O MSE é usado como um função de perda ( métrica de performance ) e representa quão bem o model ajustou aos dados de treinamento. Quanto menor o MSE, melhor o ajuste do modelo aos dados.