## Fazer previsao de classe.


# Import Libraries

In [31]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

#  Looad Dataset

In [2]:
data = pd.read_csv('train.csv')
df = data.copy()

# Data Preparation

In [3]:
feactures = ['idade', 'divida_atual', 'renda_anual',
       'valor_em_investimentos', 'taxa_utilizacao_credito', 'num_emprestimos',
       'num_contas_bancarias', 'num_cartoes_credito', 'dias_atraso_dt_venc',
       'num_pgtos_atrasados', 'num_consultas_credito', 'taxa_juros']
label = ['saldo_atual']       

In [4]:
X_tarin = df.loc[:, feactures]
y_train = df.loc[:, label]

# Model Training

In [5]:
# Model definition
lr_model = LinearRegression() # exemplo de modeledo da linear refgression

#  model fit ( ajuste de treinamento)
lr_model.fit(X_tarin, y_train)

#  previsao
y_pred = lr_model.predict(X_tarin)

In [22]:
# fazer algumas previsoes
df1 = df.loc[:, ['id_cliente','saldo_atual']]
# criar uma coluna predict
df1['predict'] = y_pred
df1.head()

id_cliente  saldo_atual     predict
0        1767   278.172008  346.669549
1       11920   268.874152  367.840277
2        8910   446.643127  431.468979
3        4964   321.141267  445.506463
4       10100   428.716114  378.271169

In [46]:
y_pred # Os valores

array([[346.66954862],
       [367.84027655],
       [431.46897895],
       ...,
       [412.25174802],
       [400.68529863],
       [455.26482252]])

In [39]:
np.sum( (X_tarin.loc[0,].values * lr_model.coef_) ) + lr_model.intercept_

array([346.66954862])

In [42]:
# fazendo o msm processo com o laco for
for i in range( len(X_tarin) ):
    print( np.sum( ( X_tarin.loc[i,].values * lr_model.coef_ ) ) + lr_model.intercept_)
    if i == 10:
        break 

[346.66954862]
[367.84027655]
[431.46897895]
[445.50646329]
[378.27116865]
[352.4833463]
[410.60408532]
[210.68563909]
[388.61996465]
[301.1477063]
[158.0964866]


In [8]:
lr_model.coef_ # coeficientes d reta

array([[ 3.96706202e-04, -4.00595601e-02,  2.77622532e-06,
        -1.04318668e-03,  9.80890872e+00, -1.22353405e-02,
        -6.33015538e-03, -3.57808095e-03, -2.15858165e+00,
         3.77570060e-04,  6.79176336e-03,  3.48471845e-03]])

In [9]:
lr_model.intercept_ # eu pegando esse comando ele e meu paramentro a0 esse valo er e construido usando os minimos quadrado

array([190.82359144])

In [ ]:
# msm que pegar a formula la em baixo
y = lr_model.intercept_ + lr_model.coef_[0][0] * X_tarin.iloc[0,0] # e assim vai ex: a2x...

In [43]:


# # estamos fazendo isso --> y = a + bx

# # com essa formula temos isso aqui -->
# y = a0 +  a1x1 +  a2x2 + a1x1 + a3x3 + a4x4 +... a12x12

# a0 = # parametros das retas que desenhamos . Sao meus parametros 
# a1 =
# a2 =
# a3 =
# a4 =
# ...
# a12 =

# x1 = # Sao minhas variaveis da feactures ou seja minhas colunas 
# x2 = 
# x3 = 
# x4 = 
# ... 
# x12 = 

# Performace

In [44]:
df.sample(4)

id_cliente  idade  saldo_atual  divida_atual  renda_anual  \
4178        7135     32   617.117049        418.54  79748.85920   
2612         550     43   337.576137       1397.24  22823.03744   
1868       10187     35   297.398622       3345.76  15675.01520   
2740        3001     31   366.686213        482.47  26169.51848   

      valor_em_investimentos  taxa_utilizacao_credito  num_emprestimos  \
4178              128.428199                35.068493                3   
2612               36.980142                27.567394                3   
1868               41.996140                39.390493                9   
2740               25.895554                31.424038                3   

      num_contas_bancarias  num_cartoes_credito  dias_atraso_dt_venc  \
4178                     3                    5                   11   
2612                     6                    9                   57   
1868                    10                    6                   47   
2740                     6                    3                   10   

      num_pgtos_atrasados  num_consultas_credito  taxa_juros investe_exterior  \
4178                   14                      7           9              Não   
2612                   14                     11          25              Não   
1868                   12                     12          23              Não   
2740                   16                      1          10              Sim   

     pessoa_polit_exp limite_adicional     predict  
4178              Não            Negar  494.407039  
2612              Não            Negar  282.319738  
1868              Não            Negar  341.703217  
2740              Não            Negar  458.165958

In [ ]:
df.dtypes

id_cliente                   int64
idade                        int64
saldo_atual                float64
divida_atual               float64
renda_anual                float64
valor_em_investimentos     float64
taxa_utilizacao_credito    float64
num_emprestimos              int64
num_contas_bancarias         int64
num_cartoes_credito          int64
dias_atraso_dt_venc          int64
num_pgtos_atrasados          int64
num_consultas_credito        int64
taxa_juros                   int64
investe_exterior            object
pessoa_polit_exp            object
limite_adicional            object
dtype: object

# diferrnca distamcia entre duas retas 
<!-- sse = soma dos erros ao quadrado 

sse -> sum squere error
ssto -> sum square total
ssr erro da reta de regresao

--> 